---
# tasks file for joe_editor
  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: http://mirror.uic.edu/EPEL/$releasever/$basearch/
      gpgcheck: no
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - name: install joe
    package:
      name: joe

  - name: "doesn't create a tilda file"
    lineinfile:
      dest: /etc/joe/joerc
      regexp: '^ ?(-nobackups.*)$'
      insertafter: 'Put each option you want set in the first column'
      line: "-nobackups     If you don't want backup files to be created"
  - name: "Force final newline when files are saved"
    lineinfile:
      dest: /etc/joe/joerc
      regexp: '^ ?(-force.*)$'
      insertafter: 'Put each option you want set in the first column'
      line: '-force         Force final newline when files are saved'
